name: Simple FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت آخرین کد
        uses: actions/checkout@v4

      - name: آپلود فایل‌های تغییر یافته به هاست از طریق FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}/
          local-dir: ./ 
          dry-run: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/vendor/*